version: '3'

services:
  slims:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slims_app
    ports:
      - "80:80"
    volumes:
      - ./files:/var/www/html/files
      - ./images:/var/www/html/images
      - ./repository:/var/www/html/repository
      - ./config:/var/www/html/config
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=slims
      - DB_USER=slims
      - DB_PASSWORD=slims_password
    restart: always

  db:
    image: mariadb:10.6
    container_name: slims_db
    ports:
      - "3306:3306"
    volumes:
      - slims_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=slims
      - MYSQL_USER=slims
      - MYSQL_PASSWORD=slims_password
    restart: always

volumes:
  slims_db_data: